// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package DB

import (
	"database/sql"
	"time"
)

type Category struct {
	ID          int64        `json:"id"`
	Name        string       `json:"name"`
	Description string       `json:"description"`
	CreatedAt   sql.NullTime `json:"created_at"`
	UpdatedAt   sql.NullTime `json:"updated_at"`
}

type Complaint struct {
	ID        int64        `json:"id"`
	ServiceID int32        `json:"service_id"`
	UserID    int32        `json:"user_id"`
	Type      string       `json:"type"`
	Complaint string       `json:"complaint"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type Day struct {
	ID        int64        `json:"id"`
	Name      string       `json:"name"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type Rating struct {
	ID        int64          `json:"id"`
	ServiceID int32          `json:"service_id"`
	UserID    int32          `json:"user_id"`
	Rating    int32          `json:"rating"`
	Comment   sql.NullString `json:"comment"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}

type Reservation struct {
	ID          int64        `json:"id"`
	ServiceID   int32        `json:"service_id"`
	UserID      int32        `json:"user_id"`
	Time        time.Time    `json:"time"`
	WeekdayID   int32        `json:"weekday_id"`
	Ranking     int32        `json:"ranking"`
	ReserveType int32        `json:"reserve_type"`
	CreatedAt   sql.NullTime `json:"created_at"`
	UpdatedAt   sql.NullTime `json:"updated_at"`
}

type ReserveType struct {
	ID        int64        `json:"id"`
	Name      string       `json:"name"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type Role struct {
	ID        int64        `json:"id"`
	Name      string       `json:"name"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type Service struct {
	ID               int64        `json:"id"`
	UserID           int32        `json:"user_id"`
	Description      string       `json:"description"`
	SubcategoryID    int32        `json:"subcategory_id"`
	GoogleMapAddress string       `json:"google_map_address"`
	Willaya          string       `json:"willaya"`
	Baladia          string       `json:"baladia"`
	CreatedAt        sql.NullTime `json:"created_at"`
	UpdatedAt        sql.NullTime `json:"updated_at"`
}

type Subcategory struct {
	ID          int64        `json:"id"`
	Name        string       `json:"name"`
	Description string       `json:"description"`
	CategoryID  int32        `json:"category_id"`
	CreatedAt   sql.NullTime `json:"created_at"`
	UpdatedAt   sql.NullTime `json:"updated_at"`
}

type User struct {
	ID          int64        `json:"id"`
	FirstName   string       `json:"first_name"`
	LastName    string       `json:"last_name"`
	PhoneNumber string       `json:"phone_number"`
	Email       string       `json:"email"`
	Password    string       `json:"password"`
	RoleID      int32        `json:"role_id"`
	CreatedAt   sql.NullTime `json:"created_at"`
	UpdatedAt   sql.NullTime `json:"updated_at"`
}

type Weekday struct {
	ID         int64        `json:"id"`
	ServiceID  int32        `json:"service_id"`
	Name       string       `json:"name"`
	OpenToWork bool         `json:"open_to_work"`
	DayID      int32        `json:"day_id"`
	StartTime  time.Time    `json:"start_time"`
	EndTime    time.Time    `json:"end_time"`
	MaxClients int32        `json:"max_clients"`
	CreatedAt  sql.NullTime `json:"created_at"`
	UpdatedAt  sql.NullTime `json:"updated_at"`
}
