// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
	"time"
)

type Category struct {
	ID          int32
	Name        string
	Description sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type Complaint struct {
	ID        int32
	ServiceID int32
	UserID    int32
	Type      string
	Complaint sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Rating struct {
	ID        int32
	ServiceID int32
	UserID    int32
	Rating    int32
	Comment   sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Reservation struct {
	ID        int32
	ServiceID int32
	UserID    int32
	Time      time.Time
	WeekdayID int32
	Ranking   sql.NullInt32
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Service struct {
	ID               int32
	UserID           int32
	Description      sql.NullString
	GoogleMapAddress sql.NullString
	Willaya          sql.NullString
	Baladia          sql.NullString
	CreatedAt        sql.NullTime
	UpdatedAt        sql.NullTime
}

type Subcategory struct {
	ID          int32
	Name        string
	Description sql.NullString
	CategoryID  int32
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type User struct {
	ID          int32
	FirstName   string
	LastName    string
	PhoneNumber string
	Email       string
	Password    string
	UserRole    string
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type Weekday struct {
	ID         int32
	ServiceID  int32
	Name       string
	StartTime  time.Time
	EndTime    time.Time
	MaxClients int32
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
}
